[package]
name = "arcana"
version = "1.0.0"
edition = "2021"
authors = ["Harry Mendez <harrymndz3@gmail.com>"]
description = "ARCANA - Un raycaster de tarot: The Fool, The Hanged Man, The Hermit"

[dependencies]
macroquad = { version = "0.4", features = ["audio"] }

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
lto = true
